"""Public request and response contracts for the Travel With Me API."""

from .common import AgentMeta
from .atlas import AtlasAgentOutput, AtlasRequest, AtlasResponse
from .flight_search import (
    FlightBaggageAllowance,
    FlightExplanationCandidate,
    FlightFareConditions,
    FlightMoney,
    FlightProviderProvenance,
    FlightSearchBudgetCeiling,
    FlightSearchCacheEntry,
    FlightSearchCacheKey,
    FlightSearchClarification,
    FlightSearchFailure,
    FlightSearchRequest,
    FlightSearchResponse,
    FlightSearchTravelerCount,
    FlightSearchUnavailableReason,
    NormalizedFlightOffer,
)
from .guide import (
    GuideAgentOutput,
    GuideConversationContext,
    GuideDay,
    GuideEvent,
    GuidePlannerState,
    GuidePlannerStateDelta,
    GuideRequest,
    GuideResponse,
    GuideStateDelta,
    GuideTripState,
)
from .meridian import (
    MeridianAdvisorConversationContext,
    MeridianAdvisorState,
    MeridianAgentOutput,
    MeridianRequest,
    MeridianResponse,
    MeridianStateDelta,
    MeridianStatus,
    MeridianTripState,
)
from .scout import ScoutAgentOutput, ScoutRequest, ScoutResponse
from .recommendations import (
    BulletDetail,
    CostBreakdownDetail,
    CostLineItem,
    CriterionEvaluation,
    EstimateRange,
    Fact,
    FactsDetail,
    RecommendationDetail,
    RecommendationOption,
    TravelerCriterion,
)

__all__ = [
    "AgentMeta",
    "AtlasAgentOutput",
    "AtlasRequest",
    "AtlasResponse",
    "FlightBaggageAllowance",
    "FlightExplanationCandidate",
    "FlightFareConditions",
    "FlightMoney",
    "FlightProviderProvenance",
    "FlightSearchBudgetCeiling",
    "FlightSearchCacheEntry",
    "FlightSearchCacheKey",
    "FlightSearchClarification",
    "FlightSearchFailure",
    "FlightSearchRequest",
    "FlightSearchResponse",
    "FlightSearchTravelerCount",
    "FlightSearchUnavailableReason",
    "NormalizedFlightOffer",
    "GuideAgentOutput",
    "GuideConversationContext",
    "GuideDay",
    "GuideEvent",
    "GuidePlannerState",
    "GuidePlannerStateDelta",
    "GuideRequest",
    "GuideResponse",
    "GuideStateDelta",
    "GuideTripState",
    "MeridianAdvisorConversationContext",
    "MeridianAdvisorState",
    "MeridianAgentOutput",
    "MeridianRequest",
    "MeridianResponse",
    "MeridianStateDelta",
    "MeridianStatus",
    "MeridianTripState",
    "BulletDetail",
    "CostBreakdownDetail",
    "CostLineItem",
    "CriterionEvaluation",
    "EstimateRange",
    "Fact",
    "FactsDetail",
    "RecommendationDetail",
    "RecommendationOption",
    "TravelerCriterion",
    "ScoutAgentOutput",
    "ScoutRequest",
    "ScoutResponse",
]
