"""Public request and response contracts for the Travel With Me API."""

from .common import AgentMeta
from .atlas import AtlasAgentOutput, AtlasRequest, AtlasResponse
from .guide import (
    GuideAgentOutput,
    GuideDay,
    GuideEvent,
    GuidePhase,
    GuidePlannerState,
    GuideRequest,
    GuideResponse,
    GuideTripState,
    GuideWorkingState,
)
from .meridian import (
    MeridianAdvisorConversationContext,
    MeridianAdvisorState,
    MeridianAgentOutput,
    MeridianRequest,
    MeridianResponse,
    MeridianStateDelta,
    MeridianStatus,
    MeridianTripState,
)
from .scout import ScoutAgentOutput, ScoutRequest, ScoutResponse
from .recommendations import (
    BulletDetail,
    CostBreakdownDetail,
    CostLineItem,
    CriterionEvaluation,
    EstimateRange,
    Fact,
    FactsDetail,
    RecommendationDetail,
    RecommendationOption,
    TravelerCriterion,
)

__all__ = [
    "AgentMeta",
    "AtlasAgentOutput",
    "AtlasRequest",
    "AtlasResponse",
    "GuideAgentOutput",
    "GuideDay",
    "GuideEvent",
    "GuidePhase",
    "GuidePlannerState",
    "GuideRequest",
    "GuideResponse",
    "GuideTripState",
    "GuideWorkingState",
    "MeridianAdvisorConversationContext",
    "MeridianAdvisorState",
    "MeridianAgentOutput",
    "MeridianRequest",
    "MeridianResponse",
    "MeridianStateDelta",
    "MeridianStatus",
    "MeridianTripState",
    "BulletDetail",
    "CostBreakdownDetail",
    "CostLineItem",
    "CriterionEvaluation",
    "EstimateRange",
    "Fact",
    "FactsDetail",
    "RecommendationDetail",
    "RecommendationOption",
    "TravelerCriterion",
    "ScoutAgentOutput",
    "ScoutRequest",
    "ScoutResponse",
]
