"""Guide API contracts and working-plan ownership validation."""

from typing import Annotated, Any, Literal, Optional

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    model_validator,
)

from ..trust_boundary import validate_phase_state
from .common import AgentMeta
from .scout import BoundedMessage


GuideText = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]
GuidePace = Literal["relaxed", "balanced", "packed"]
GuideEvent = Literal["START", "TRAVELER_MESSAGE", "APPROVE_PLACES", "APPROVE_PLAN"]
GuidePhase = Literal[
    "NEEDS_CLARIFICATION",
    "PLACES_DRAFT",
    "DAY_PLAN_DRAFT",
    "PLAN_APPROVED",
]
GuideChangedField = Literal[
    "destinations",
    "duration_days",
    "start_date",
    "places",
    "day_plan",
    "preferences",
    "exclusions",
]


class GuideDay(BaseModel):
    model_config = ConfigDict(extra="forbid")

    day_number: int = Field(ge=1)
    date: Optional[str] = None
    places: list[GuideText] = Field(default_factory=list)
    pace: GuidePace
    buffer_note: Optional[GuideText] = None


class GuideWorkingState(BaseModel):
    """Guide state accepted from a caller before the next generated turn."""

    model_config = ConfigDict(extra="forbid")

    phase: Optional[GuidePhase] = None
    destinations: list[GuideText] = Field(default_factory=list)
    duration_days: Optional[int] = Field(default=None, ge=1)
    start_date: Optional[str] = None
    places: list[GuideText] = Field(default_factory=list)
    day_plan: list[GuideDay] = Field(default_factory=list)
    preferences: list[GuideText] = Field(default_factory=list)
    exclusions: list[GuideText] = Field(default_factory=list)
    applied_changes: list[GuideText] = Field(default_factory=list)
    pending_clarification: Optional[GuideText] = None


class GuideTripState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    trip_context: dict[str, Any] = Field(default_factory=dict)
    guide_state: GuideWorkingState = Field(default_factory=GuideWorkingState)


class GuideRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    event: GuideEvent = "START"
    trip_state: GuideTripState = Field(default_factory=GuideTripState)
    message: Optional[BoundedMessage] = None

    @model_validator(mode="after")
    def validate_request(self) -> "GuideRequest":
        if self.event == "TRAVELER_MESSAGE" and not (
            self.message and self.message.strip()
        ):
            raise ValueError("TRAVELER_MESSAGE requires a non-empty message")
        validate_phase_state(self.trip_state.model_dump())
        return self


class GuidePlannerState(BaseModel):
    """Full replacement state generated by Guide on every successful turn."""

    model_config = ConfigDict(extra="forbid")

    phase: GuidePhase
    destinations: list[GuideText]
    duration_days: Optional[int] = Field(ge=1)
    start_date: Optional[str]
    places: list[GuideText]
    day_plan: list[GuideDay]
    preferences: list[GuideText]
    exclusions: list[GuideText]
    applied_changes: list[GuideText]
    pending_clarification: Optional[GuideText]

    @model_validator(mode="after")
    def validate_working_plan(self) -> "GuidePlannerState":
        self._validate_unique_lists()
        self._validate_clarification()
        self._validate_day_plan()
        return self

    def _validate_unique_lists(self) -> None:
        for name, values in (
            ("destinations", self.destinations),
            ("places", self.places),
            ("preferences", self.preferences),
            ("exclusions", self.exclusions),
        ):
            normalized = [value.casefold() for value in values]
            if len(normalized) != len(set(normalized)):
                raise ValueError(f"{name} must be unique")

    def _validate_clarification(self) -> None:
        if self.phase == "NEEDS_CLARIFICATION":
            if self.pending_clarification is None:
                raise ValueError(
                    "NEEDS_CLARIFICATION requires pending_clarification"
                )
            return
        if self.pending_clarification is not None:
            raise ValueError(
                "pending_clarification is allowed only for NEEDS_CLARIFICATION"
            )

    def _validate_day_plan(self) -> None:
        if self.phase in {"NEEDS_CLARIFICATION", "PLACES_DRAFT"}:
            if self.day_plan:
                raise ValueError(f"{self.phase} does not allow a day plan")
            return

        if self.duration_days is None:
            raise ValueError(f"{self.phase} requires duration_days")
        if len(self.day_plan) != self.duration_days:
            raise ValueError("day plan length must equal duration_days")
        day_numbers = [day.day_number for day in self.day_plan]
        if day_numbers != list(range(1, self.duration_days + 1)):
            raise ValueError("day numbers must be sequential from 1")

        allocated = [place for day in self.day_plan for place in day.places]
        if len(allocated) != len({place.casefold() for place in allocated}):
            raise ValueError("each place must be allocated exactly once")
        if {place.casefold() for place in allocated} != {
            place.casefold() for place in self.places
        }:
            raise ValueError("day plan must allocate every place and no others")


GuideOutcome = Literal["continue", "reopen_destination_discovery"]


class GuideAgentOutput(BaseModel):
    """Canonical generated Guide output before Backend provenance is attached."""

    model_config = ConfigDict(extra="forbid")

    message: GuideText
    guide_state: GuidePlannerState
    explicit_changes: list[GuideChangedField]
    outcome: GuideOutcome = "continue"

    @model_validator(mode="after")
    def validate_explicit_changes(self) -> "GuideAgentOutput":
        if len(self.explicit_changes) != len(set(self.explicit_changes)):
            raise ValueError("explicit_changes must be unique")
        return self


class GuideResponse(GuideAgentOutput):
    agent_meta: AgentMeta
