"""Meridian API contracts and ownership validation."""

from typing import Annotated, Any, Literal, Optional

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    ValidationInfo,
    field_validator,
    model_validator,
)

from .agent_contract import (
    AgentContent,
    EmptyAsNone,
    NullAsDefault,
    Text,
    case_insensitive,
    clean_title,
    derived,
    ensure_unique,
    record_heal,
)
from .common import AgentMeta
from .recommendations import RecommendationOption, TravelerCriterion
from .scout import (
    BoundedMessage,
    ScoutAdvisorConversationContext,
    ScoutAdvisorState,
)
from .trip_context import TripContext
from ..trust_boundary import (
    assert_agent_delta_within_boundary,
    assert_no_destination_claim,
    validate_phase_state,
)


MeridianAdvisorConversationContext = ScoutAdvisorConversationContext
MeridianAdvisorState = ScoutAdvisorState


class MeridianTripState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    trip_context: TripContext = Field(default_factory=TripContext)
    advisor_state: ScoutAdvisorState = Field(default_factory=ScoutAdvisorState)
    matcher_state: dict[str, Any] = Field(default_factory=dict)
    # TWM-232: read-only visibility into the trip's current title so Meridian
    # can tell whether one is already set -- the same presence check it
    # already does for any trip_context field -- before deciding whether to
    # generate one. None/the placeholder both read as "not set yet".
    current_title: Optional[str] = None


class MeridianRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    trip_state: MeridianTripState = Field(default_factory=MeridianTripState)
    message: Optional[BoundedMessage] = None

    @model_validator(mode="after")
    def validate_untrusted_state(self) -> "MeridianRequest":
        validate_phase_state(self.trip_state.model_dump())
        return self


class MeridianStateDelta(BaseModel):
    model_config = ConfigDict(extra="forbid")

    trip_context: TripContext = Field(default_factory=TripContext)
    matcher_state: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def reject_ui_owned_state(self) -> "MeridianStateDelta":
        assert_agent_delta_within_boundary(self)
        assert_no_destination_claim(self)
        return self


MeridianStatus = case_insensitive(
    Literal[
        "NEEDS_CLARIFICATION",
        "SUCCESS",
        "SOFT_FAIL",
        "HARD_FAIL",
        "BUDGET_FAIL",
        "CONFLICT_FAIL",
    ]
)

_OPTION_STATUSES = {"SUCCESS", "SOFT_FAIL"}
_FAILURE_STATUSES = {"SOFT_FAIL", "HARD_FAIL", "BUDGET_FAIL", "CONFLICT_FAIL"}
MAX_OPTIONS = 3


class MeridianAgentOutput(AgentContent):
    """Canonical structured output generated by either Meridian runtime.

    The model decides the status, the message, the criteria, and each option's
    evaluations and relative order. Everything else -- rank numbers, the
    option-set ``trip_type``, and the conversation bookkeeping on
    ``matcher_state.conversation_context`` -- is Backend-derived here, so a
    slip in any of them can no longer fail an otherwise good recommendation.
    """

    status: MeridianStatus
    state_delta: Annotated[MeridianStateDelta, NullAsDefault] = Field(default_factory=MeridianStateDelta)
    message: Text
    generated_at: Optional[str] = None
    # Derived from the options below; hidden from the schema shown to the model.
    trip_type: Optional[Literal["single", "circuit", "mixed"]] = derived(default=None)
    traveler_criteria: Annotated[Optional[list[TravelerCriterion]], EmptyAsNone] = None
    options: list[RecommendationOption] = Field(default_factory=list, max_length=MAX_OPTIONS)
    constraint_adjustment_suggestions: Annotated[Optional[list[Text]], EmptyAsNone] = None

    @field_validator("options", mode="before")
    @classmethod
    def _rank_and_cap_options(cls, value: Any, info: ValidationInfo) -> Any:
        """The model's own ordering is its ranking: sort by any rank it gave
        (stable), keep the top ``MAX_OPTIONS``, and number them 1..n. Rank is
        a position, so duplicates, gaps, or a fourth option are not reasons to
        discard a whole recommendation."""

        if not isinstance(value, list) or not all(isinstance(item, dict) for item in value):
            return value
        ranks = [item.get("rank") for item in value]
        ordered = (
            sorted(value, key=lambda item: item["rank"])
            if all(isinstance(rank, int) for rank in ranks)
            else list(value)
        )
        kept = [{**item, "rank": position} for position, item in enumerate(ordered[:MAX_OPTIONS], 1)]
        if kept != value:
            record_heal(info, "options.ranked_by_position")
        return kept

    @model_validator(mode="after")
    def validate_outcome(self, info: ValidationInfo) -> "MeridianAgentOutput":
        self._validate_status_options()
        self._validate_option_consistency()
        self._derive_trip_type()
        self._derive_conversation_context(info)
        self._clean_generated_title(info)
        self._validate_soft_fail_tradeoffs()
        self._drop_misplaced_suggestions(info)
        return self

    def _validate_status_options(self) -> None:
        if self.status in _OPTION_STATUSES:
            if not self.traveler_criteria:
                raise ValueError(f"{self.status} requires traveler criteria")
            if not self.options:
                raise ValueError(f"{self.status} requires at least one valid option")
            return
        if self.traveler_criteria is not None:
            raise ValueError(f"{self.status} does not allow traveler criteria")
        if self.options:
            raise ValueError(f"{self.status} does not allow recommendation options")

    def _validate_option_consistency(self) -> None:
        if not self.options:
            return

        catalog = self.traveler_criteria or []
        ensure_unique([criterion.id for criterion in catalog], "traveler criterion ids")
        ensure_unique([criterion.label for criterion in catalog], "traveler criterion labels")
        criteria_by_id = {criterion.id.casefold(): criterion for criterion in catalog}

        ensure_unique(
            [f"{option.type}:{option.destination_id or option.circuit_id}" for option in self.options],
            "recommendation option identities",
        )

        expected_criteria = set(criteria_by_id)
        for option in self.options:
            option_criteria = {evaluation.criterion_id.casefold() for evaluation in option.evaluations}
            if option_criteria != expected_criteria:
                raise ValueError("every option must evaluate every traveler criterion exactly once")
            for evaluation in option.evaluations:
                criterion = criteria_by_id[evaluation.criterion_id.casefold()]
                if criterion.requirement_type == "HARD" and evaluation.outcome == "MISMATCH":
                    raise ValueError("a hard requirement cannot have a mismatch outcome")

    def _derive_trip_type(self) -> None:
        types = {option.type for option in self.options}
        self.trip_type = None if not types else "mixed" if len(types) > 1 else next(iter(types))

    def _derive_conversation_context(self, info: ValidationInfo) -> None:
        """The visible message is always the last Meridian message, and only a
        clarification is still awaiting something -- both are facts about the
        status and message, not decisions for the model to repeat."""

        matcher_state = self.state_delta.matcher_state
        context = matcher_state.get("conversation_context")
        if not isinstance(context, dict):
            context = matcher_state["conversation_context"] = {}
        if self.status == "NEEDS_CLARIFICATION":
            awaiting = context.get("awaiting")
            if not isinstance(awaiting, str) or not awaiting.strip():
                raise ValueError("NEEDS_CLARIFICATION requires one non-empty awaiting value")
        else:
            if context.get("awaiting") is not None:
                record_heal(info, "awaiting.cleared_on_terminal_outcome")
            context["awaiting"] = None
        context["last_meridian_message"] = self.message
        # The one canonical home is inside conversation_context.
        matcher_state.pop("last_meridian_message", None)

    def _clean_generated_title(self, info: ValidationInfo) -> None:
        """The title is stored in a 120-character column; whatever the model
        produced is made storable, or dropped."""

        matcher_state = self.state_delta.matcher_state
        if "generated_title" not in matcher_state:
            return
        cleaned = clean_title(matcher_state["generated_title"])
        if cleaned != matcher_state["generated_title"]:
            record_heal(info, "generated_title.cleaned")
        if cleaned is None:
            del matcher_state["generated_title"]
        else:
            matcher_state["generated_title"] = cleaned

    def _validate_soft_fail_tradeoffs(self) -> None:
        if self.status != "SOFT_FAIL":
            return
        for option in self.options:
            has_criterion_tradeoff = any(
                evaluation.outcome in {"TRADEOFF", "MISMATCH"} for evaluation in option.evaluations
            )
            if not option.other_considerations and not has_criterion_tradeoff:
                raise ValueError("every SOFT_FAIL option requires a visible trade-off")

    def _drop_misplaced_suggestions(self, info: ValidationInfo) -> None:
        """Adjustment suggestions only mean something on a failure outcome."""

        if self.constraint_adjustment_suggestions and self.status not in _FAILURE_STATUSES:
            self.constraint_adjustment_suggestions = None
            record_heal(info, "constraint_adjustment_suggestions.dropped_on_non_failure")


class MeridianResponse(MeridianAgentOutput):
    """Public Meridian response with deterministic Backend provenance."""

    agent_meta: AgentMeta
